services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot/carts:/app/bot/carts
    depends_on:
      - db
    command: uv run bot/main.py

    develop:
      watch:
        - action: sync
          path: ./bot
          target: /app/bot
          ignore:
            - __pycache__/
            - .venv/
            - db/__pycache__/
            - bot/__pycache__/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock

  db:
    image: postgres:15-alpine
    container_name: telegram_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
